### PR TITLE
added the location and updated the table

### PR DESCRIPTION
**Pull request by prahasR**

### CODE REVIEW

**Comment by iamshreeram** [comment]
@prahasR , Thanks for raising PR. 

Few of the changes that I made are missing. Could you please do `git pull` before making changes to the code. 

( OR )
You could, 
1. clone the repo (`git clone https://github.com/iamshreeram/hacktoberfest-2021.git`) again and 
2. cut a branch ( `git checkout -b prahas-changes`)
3. make the changes that you did 
4. Add it all `git add *`, 
5. commit it - `git commit -m "Adding location"`, and 
6. push your branch `git push origin prahas-changes`

Method 2 is right way of pushing the changes.

**Comment by iamshreeram** [comment]
I have updated [How to contribute](https://github.com/iamshreeram/hacktoberfest-2021#how-to-contribute). See If this helps.

**Comment by prahasR** [comment]
@iamshreeram Thanks for the help, I just tried method 2 but it is saying "Permission to iamshreeram/hacktoberfest-2021.git denied to prahasR." . Can you help me with this. I think I can make changes to the forked repo only . And as I have already forked your repository so now I have to pull the changes you made after my forking...right? Can you please help me with doing this

**Comment by iamshreeram** [comment]
@prahasR , Thats right. You should be a collaborator or you will have to fork (this will in-turn create a new branch) and push it to master. 

I made you as a collaborator to manage this repository. You should be able to push your changes to the repository directly now and also, you can manage the changes that others push. 

Please try it now and let me know. 

PS: Always please pull the latest changes `git pull` from the repository before pushing your changes.

**Comment by prahasR** [comment]
@iamshreeram Can you check now ...I resolved the conflict ....please let me know if you are able to merge my changes now?

**Comment by iamshreeram** [comment]
@prahasR , Merged your changes!

**Comment by prahasR** [comment]
Hey @iamshreeram I am glad that you merged it. Just wanted to ask whether it will be counted for hacktoberfest or not. I checked my profile and it is saying that "Matures in 14 days" . Can you help me by clarify this a little. What does it mean. Again happy to conribute

**Comment by iamshreeram** [comment]
@prahasR , Yes, this will be counted.

**Pull request merged**
